- back/actions/planets/doadd.php
- back/actions/planets/dodelete.php
- back/actions/planets/doedit.php
- back/actions/planets/edit.php
- back/actions/station/doadd.php
- back/actions/station/dodelete.php
- back/actions/station/doedit.php
- back/actions/station/edit.php
- back/db_space.sql
- back/includes/connection.php
- back/includes/head.php
- back/index.php
- package-lock.json
- package.json
- yarn.lock
> 🗃Added back-office

- back/actions/planets/doadd.php
- back/actions/ship/doadd.php
- back/actions/ship/dodelete.php
- back/actions/ship/doedit.php
- back/actions/ship/edit.php
- back/actions/station/doadd.php
- back/actions/station/dodelete.php
- back/actions/station/doedit.php
- back/actions/station/edit.php
- back/includes/head.php
- back/index.php
- public/index.html
- src/scss/components/_header.scss
- src/scss/global/_fonts.scss
> ✨ Added image feature and some stuff

- documentation.md
> 📝 Research about scroll parallax

- public/sign.html
- src/js/ui.js
- src/scss/components/_sign.scss
> 💄 Update sign.html

- src/scss/components/_sign.scss
> 🐛 Version bug

- public/sign.html
> 🚑 delete sign.html by error

- public/userform.html
- src/scss/components/_userform.scss
- src/scss/global/_global.scss
>  ✨ added formula

- public/sign.html
> 🐛 Update index.html

- back/actions/login/check.php
- back/actions/login/doadd.php
- back/actions/login/doedit.php
- back/actions/login/edit.php
- back/actions/login/logout.php
- public/index.php
- public/profile.php
- public/sign.php
- public/userform.php
- src/scss/components/_userform.scss
Fixes issue #52 
*PHP is becoming one of my most favorite language...* 🥇
> ✨ Adding PHP on most files ❤️

- public/index.php
- public/profile.php
- public/userform.php
- src/scss/components/_menu.scss
- src/scss/components/_sign.scss
- src/scss/components/_userform.scss
> 🎨Changed CSS from HTML to new CSS files

- public/index.html
- src/js/ui.js
- src/scss/components/_home.scss
- src/scss/components/_menu.scss
- src/scss/components/_sign.scss
- src/scss/components/_userform.scss
- src/scss/global/_global.scss
> 💄 Finish home.html

- public/aiopacks.html
- public/userform.html
- src/js/app.js
- src/js/ui.js
- src/scss/components/_aio.scss
- src/scss/components/_footer.scss
> 📱 Add desktop version

- back/includes/connection.php
- public/spaceships.php
Fixes issue #77 ![bitmoji](https://render.bitstrips.com/v2/cpanel/6cd83ca1-68db-4dfb-a0e5-ca72d017a5b2-f2a69005-03db-455b-b918-18ad88c2cbd8-v1.png?transparent=1&palette=1&width=246)
> ✨ Added Spaceships dynamic content

- public/planets.php
> ✨ Added dynamic content into planets

- public/spacemodules.php
Fixes #80 ! ![bitmoji](https://render.bitstrips.com/v2/cpanel/72773798-2aa6-46a5-8e43-71a636ea9fdd-f2a69005-03db-455b-b918-18ad88c2cbd8-v1.png?transparent=1&palette=1&width=246)
> ✨ Added dynamic support into stations

- back/actions/login/check.php
- public/aiopacks.html
- public/index.php
- public/packdesc.html
- public/profile.php
- src/scss/components/_aio.scss
- src/scss/components/_packdesc.scss
- src/scss/global/_variables.scss
- src/scss/master.scss
> 🚧 Create packdesc.html

- public/spaceship.html
- src/js/ui.js
- src/scss/components/_spaceship.scss
- src/scss/master.scss
> ✨ Update spaceship.html

- public/profile.php
- src/scss/components/_profile.scss
- src/scss/master.scss
> Added beginning of profile page

- public/spaceship.html
- src/scss/components/_spaceship.scss
- src/scss/global/_global.scss
> 🚧 Update spaceship.html

- public/spacemodules.html
- public/spaceship.html
- src/scss/components/_planets.scss
- src/scss/components/_spacemodules.scss
- src/scss/components/_spaceship.scss
- src/scss/components/_spaceships.scss
> 💄 Finish spaceship.html

- back/includes/connection.php
- package-lock.json
- public/profile.php
- src/scss/components/_profile.scss
must verify the footer on desktop format
> 💄 finished profile style

- public/planet.html
- public/spaceship.html
- src/js/ui.js
- src/scss/components/_planet.scss
- src/scss/master.scss
> ✨ Create planet.html

- back/includes/connection.php
- public/custompacks.php
- src/scss/components/_custom.scss
- src/scss/components/_spaceship.scss
> ✨ Create custompacks.html

- public/payment.html
- public/userform.php
- src/scss/components/_payment.scss
- src/scss/master.scss
plus modified smthg in userform.scss
> 💄  finished payment page

- back/actions/planets/doadd.php
- back/actions/planets/doedit.php
- back/actions/planets/edit.php
- back/actions/ship/doadd.php
- back/actions/ship/doedit.php
- back/actions/ship/edit.php
- back/actions/station/doadd.php
- back/actions/station/doedit.php
- back/actions/station/edit.php
- back/includes/connection.php
- back/index.php
- public/custompacks.php
- public/packdesc.html
- public/planet.php
- public/sign.php
- public/spacemodule.php
- public/spacemodules.php
- public/spaceship.php
Fixes issues #48 #49 #50 and optimised content.
> ⚠️ Added very, very, very much content

- public/index.php
- src/scss/global/_global.scss
> ✨ Replace lorem text

- public/spacemodules.php
- src/scss/components/_menu.scss
> ✨ Replace lorem in spacemodules.php

- public/aiopacks.php
- public/buy.php
- public/confirmation.php
- public/custompacks.php
- public/payment.php
- public/userform.php
> 🗃 Add all data spaceship/planets/spacemodule param

- back/lastdb.sql
> 🗃 Add new data with ALL desc
